language: erlang

otp_release:
  - 23.0
  - 22.0
  - 21.1
  - 20.0
before_script:
  - kerl list installations
  - curl -O https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
  - rm -fr ${HOME}/stockfish-10-linux
  - rm -f ${HOME}/stockfish-10-linux.zip
  - curl https://stockfishchess.org/files/stockfish-10-linux.zip -o ${HOME}/stockfish-10-linux.zip
  - unzip ${HOME}/stockfish-10-linux.zip -d ${HOME}
  - chmod +x ${HOME}/stockfish-10-linux/Linux/stockfish_10_x64
script:
  - UCI_ENGINE_PATH=${HOME}/stockfish-10-linux/Linux/stockfish_10_x64 ./rebar3 ct
  - ./rebar3 cover
  - ./rebar3 covertool generate
  - ./rebar3 dialyzer
after_success:
  - bash <(curl -s https://codecov.io/bash) -f _build/test/covertool/binbo.covertool.xml
branches:
  only:
  - master
  - develop
cache:
  directories:
    - _build
    - "$HOME/.cache/rebar3"
