language: erlang

otp_release:
  - 22.0
  - 21.3
  - 20.3
  - 19.0
before_script: curl -O https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
script:
  - ./rebar3 do dialyzer, ct
branches:
  only:
  - master
cache:
  directories:
    - _build
